#ifndef SPOLAB3_CONST_H
#define SPOLAB3_CONST_H
#define USERNAME_SIZE 21
#define BASE_10 10
#define MESSAGE_SIZE 500
#define MAX_MESSAGE_STRUCT_SIZE 552
#define TIME_T_SIZE 8
#define HOSTNAME "127.0.0.1"
#define DATE_STRING_SIZE 22
#define HISTORY_BUFFER_SIZE 50
#endif //SPOLAB3_CONST_H
